name: Fly Deploy
on:
  push:
    branches:
      - main
on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line


jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app url-monitor --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Start machines after deploy
        run: |
          fly machines list --app url-monitor | awk '/app/ {print $1}' | xargs -I {} fly machine start {}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
